services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
  main-db:
    image: postgres:16.1
    container_name: main-db
    ports:
      - "4432:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main