services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d stats"]
      interval: 10s
      timeout: 5s
      retries: 5

  main-db:
    image: postgres:16.1
    container_name: main-db
    ports:
      - "4432:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d main"]
      interval: 10s
      timeout: 5s
      retries: 5