analyzer:
  kafka:
    user-action-consumer-props:
      bootstrapServers: "localhost:9092"
      groupId: "analyzer-group"
      keyDeserializer: "org.apache.kafka.common.serialization.LongDeserializer"
      valueDeserializer: "ru.practicum.stats.avro.UserActionDeserializer"
      enableAutoCommit: "false"
      autoOffsetReset: "earliest"
    event-similarity-consumer-props:
      bootstrapServers: "localhost:9092"
      groupId: "analyzer-group"
      keyDeserializer: "org.apache.kafka.common.serialization.LongDeserializer"
      valueDeserializer: "ru.practicum.stats.avro.EventSimilarityDeserializer"
      enableAutoCommit: "false"
      autoOffsetReset: "earliest"
    userActionsTopic: "stats.user-actions.v1"
    eventsSimilarityTopic: "stats.events-similarity.v1"